### ISSUE TITLE
Plugin doesn't work for iOS

### ISSUE THREAD

**Issue by volodymyrl** [encke/wazelink#2]
Plugin works on Android but doesn't work on iOS and when I tried remove it by 
```
cordova plugin rm cr.encke.WazeLink 
```
I got an error 
```
Uninstalling cr.encke.WazeLink from android
TypeError: Cannot read property 'trim' of null
    at new SemVer (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/semver/semver.js:268:18)
    at compare (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/semver/semver.js:424:10)
    at Function.gte (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/semver/semver.js:473:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/uninstall.js:344:45
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
```

**Comment by encke** [comment]
The plugin is wazelink. Type cordova plugin rm cr.encke.wazelink

**Comment by volodymyrl** [comment]
@encke thanks for your answer, but when I run your command I got an error

Admins-Mac-mini:$ cordova plugin rm cr.encke.wazelink
Plugin "cr.encke.wazelink" is not present in the project. See `cordova plugin list`.
Admins-Mac-mini:$ cordova plugin list
com.ionic.keyboard 1.0.4 "Keyboard"
cr.encke.WazeLink 1.0.1 "WazeLink"

**Comment by encke** [comment]
No Problem!  Give me a couple of hours to get to my workstation and I'll see what I can do

**Comment by encke** [comment]
I see an error on the package definition, please run:
	cordova plugin rm cr.encke.WazeLink.WazeLink

This should remove the plugin with no issue. I will work on an update to the package now.

Matthew

**Comment by volodymyrl** [comment]
Plugin "cr.encke.WazeLink.WazeLink" is not present in the project. See `cordova plugin list`.

cr.encke.WazeLink 1.0.1 "WazeLink"

Still have the same issue
